# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
GET http://localhost:8080/api/board
Accept: application/json

###

GET http://localhost:8080/api/users
Accept: application/json

###

DELETE http://localhost:8080/delete/board/1
Accept: application/json

###

DELETE http://localhost:8080/delete/users/1
Accept: application/json

###

POST http://localhost:8080/add/board
Content-Type: application/json

{
  "userId": 2,
  "title": "title2222222",
  "content": "content2222222"
}

###

POST http://localhost:8080/add/users
Content-Type: application/json

{
  "account": "test0111111",
  "password": "passwordddddddd",
  "username": "test0111111",
  "email": "test0111111@dgsw.hs.kr"
}

###

PUT http://localhost:8080/modify/board
Content-Type: application/json

{
  "id": 1,
  "userId": 2,
  "title": "title11111",
  "content": "content111111"
}

###

PUT http://localhost:8080/modify/users
Content-Type: application/json

{
  "id": 7,
  "account": "test",
  "password": "pas",
  "username": "tes",
  "email": "te@dgsw.hs.kr"
}

###

GET http://localhost:8080/get/board/4
Accept: application/json

###

GET http://localhost:8080/get/users/4
Accept: application/json

###

GET http://localhost:8080/getByUserId/board/2
Accept: application/json

###

POST http://localhost:8080/addHash/board
Content-Type: application/json

{
  "userId": 3,
  "title": "333333",
  "content": "333333333333"
}

###